#ifndef WEB_DASHBOARD_H
#define WEB_DASHBOARD_H

/**
 * @brief Interfaz Web SPA (Single Page Application) moderna para la Tostadora de Café IoT.
 *        Diseñada exactamente con base en la referencia visual del dashboard:
 *        - Paleta de colores profesionales (#0f172a, #f8fafc, acentos verde, azul, naranja, violeta).
 *        - Modos de tostión 1 (Bajo), 2 (Medio), 3 (Alto) y Manual.
 *        - Stepper del proceso: LISTO -> Precalentando -> Tostión -> Enfriamiento.
 *        - Sliders interactivos de potencia PWM (Resistencia, Blower, Motor).
 *        - Telemetría en tiempo real: Cronómetro, Temperatura actual vs objetivo con barra,
 *          Estimación de energía (kW/kWh), Peso cargado (HX711) y velocidad de actuadores.
 *        - Alerta visual inmediata de sobretemperatura de seguridad (>= 225 °C).
 */

static const char WEB_DASHBOARD_HTML[] = 
"<!DOCTYPE html>\n"
"<html lang=\"es\">\n"
"<head>\n"
"<meta charset=\"UTF-8\">\n"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"<title>Tostadora de Café IoT</title>\n"
"<style>\n"
":root {\n"
"  --bg-main: #f1f5f9;\n"
"  --bg-card: #ffffff;\n"
"  --sidebar-bg: #0f172a;\n"
"  --sidebar-text: #94a3b8;\n"
"  --sidebar-active: #2563eb;\n"
"  --text-main: #1e293b;\n"
"  --text-muted: #64748b;\n"
"  --border: #e2e8f0;\n"
"  --primary: #2563eb;\n"
"  --success: #10b981;\n"
"  --warning: #f59e0b;\n"
"  --danger: #ef4444;\n"
"  --purple: #8b5cf6;\n"
"  --mode-low: #10b981;\n"
"  --mode-med: #2563eb;\n"
"  --mode-high: #f97316;\n"
"}\n"
"* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }\n"
"body { background: var(--bg-main); color: var(--text-main); display: flex; min-height: 100vh; }\n"
"/* Sidebar */\n"
".sidebar { width: 170px; background: var(--sidebar-bg); color: var(--sidebar-text); display: flex; flex-direction: column; justify-content: space-between; padding: 20px 10px; flex-shrink: 0; }\n"
".sidebar-brand { display: flex; align-items: center; gap: 8px; color: #fff; font-size: 13px; font-weight: 700; margin-bottom: 25px; padding-left: 6px; }\n"
".sidebar-menu a { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 8px; color: #fff; text-decoration: none; font-size: 13px; font-weight: 600; background: var(--sidebar-active); margin-bottom: 8px; }\n"
".sidebar-bottom a { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 8px; color: #cbd5e1; text-decoration: none; font-size: 13px; cursor: pointer; transition: 0.2s; }\n"
".sidebar-bottom a:hover { background: #334155; color: #ef4444; }\n"
"/* Main Container */\n"
".main-wrapper { flex: 1; display: flex; flex-direction: column; overflow-x: hidden; }\n"
"/* Top Header */\n"
".top-header { background: #0b1329; color: #fff; padding: 12px 24px; display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #1e293b; }\n"
".header-title { display: flex; align-items: center; gap: 10px; font-size: 18px; font-weight: 700; }\n"
".header-status { display: flex; align-items: center; gap: 18px; font-size: 13px; color: #cbd5e1; }\n"
".badge-dot { width: 8px; height: 8px; border-radius: 50%; background: #10b981; display: inline-block; box-shadow: 0 0 8px #10b981; animation: pulse 2s infinite; }\n"
"@keyframes pulse { 0%{opacity:1;} 50%{opacity:0.4;} 100%{opacity:1;} }\n"
"/* Content Body */\n"
".content-area { padding: 20px; display: flex; flex-direction: column; gap: 20px; max-width: 1400px; margin: 0 auto; width: 100%; }\n"
"/* Top Row Cards */\n"
".hero-row { display: grid; grid-template-columns: 2fr 1fr 1fr; gap: 16px; }\n"
".hero-card { background: var(--bg-card); border-radius: 12px; padding: 16px 20px; border: 1px solid var(--border); display: flex; align-items: center; gap: 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); }\n"
".status-icon-box { width: 48px; height: 48px; border-radius: 50%; background: #dcfce7; color: #16a34a; display: flex; align-items: center; justify-content: center; font-size: 24px; flex-shrink: 0; }\n"
".status-icon-box.preheat { background: #fef3c7; color: #d97706; }\n"
".status-icon-box.roast { background: #fee2e2; color: #dc2626; }\n"
".status-icon-box.cool { background: #e0f2fe; color: #0284c7; }\n"
".status-icon-box.alarm { background: #991b1b; color: #fff; animation: pulse 0.5s infinite; }\n"
".hero-info h2 { font-size: 20px; font-weight: 800; letter-spacing: 0.5px; }\n"
".hero-info p { font-size: 13px; color: var(--text-muted); margin-top: 2px; }\n"
".cafe-icon-box, .wifi-icon-box { width: 44px; height: 44px; border-radius: 10px; background: #f8fafc; border: 1px solid var(--border); display: flex; align-items: center; justify-content: center; flex-shrink: 0; }\n"
"/* Main 3-Column Layout */\n"
".dashboard-grid { display: grid; grid-template-columns: 1.15fr 1fr 1fr; gap: 18px; align-items: start; }\n"
"/* Card Containers */\n"
".card { background: var(--bg-card); border-radius: 12px; border: 1px solid var(--border); padding: 18px; box-shadow: 0 1px 3px rgba(0,0,0,0.05); margin-bottom: 16px; }\n"
".card:last-child { margin-bottom: 0; }\n"
".card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 14px; }\n"
".card-header h3 { font-size: 14px; font-weight: 700; color: var(--text-main); display: flex; align-items: center; gap: 8px; }\n"
".badge-state { font-size: 11px; font-weight: 700; padding: 3px 8px; border-radius: 12px; background: #e2e8f0; color: #475569; text-transform: uppercase; }\n"
".badge-state.ready { background: #dcfce7; color: #16a34a; }\n"
".badge-state.active { background: #fee2e2; color: #dc2626; }\n"
".badge-state.preheat { background: #fef3c7; color: #b45309; }\n"
".badge-state.cool { background: #e0f2fe; color: #0284c7; }\n"
"/* Mode Selection Cards */\n"
".modes-row { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; margin-bottom: 12px; }\n"
".mode-box { border: 2px solid var(--border); border-radius: 10px; padding: 12px 6px; text-align: center; cursor: pointer; transition: all 0.2s ease; background: #fff; }\n"
".mode-box:hover { transform: translateY(-2px); box-shadow: 0 4px 10px rgba(0,0,0,0.06); }\n"
".mode-box.selected { border-width: 2px; box-shadow: 0 0 0 1px rgba(0,0,0,0.05); }\n"
".mode-box.m1.selected { border-color: var(--mode-low); background: #f0fdf4; }\n"
".mode-box.m2.selected { border-color: var(--mode-med); background: #eff6ff; }\n"
".mode-box.m3.selected { border-color: var(--mode-high); background: #fff7ed; }\n"
".mode-box svg { width: 28px; height: 28px; margin-bottom: 6px; }\n"
".mode-title { font-size: 13px; font-weight: 700; }\n"
".mode-sub { font-size: 11px; color: var(--text-muted); margin-top: 2px; }\n"
".mode-target { font-size: 10px; font-weight: 700; padding: 2px 4px; border-radius: 4px; background: #f1f5f9; display: inline-block; margin-top: 5px; }\n"
".mode-manual { border: 2px solid var(--border); border-radius: 10px; padding: 12px 14px; display: flex; align-items: center; gap: 12px; cursor: pointer; transition: 0.2s; background: #fff; }\n"
".mode-manual.selected { border-color: var(--purple); background: #f5f3ff; }\n"
".mode-manual svg { width: 24px; height: 24px; color: var(--purple); }\n"
"/* Stepper Timeline */\n"
".stepper-list { display: flex; flex-direction: column; gap: 18px; position: relative; padding-left: 10px; margin: 10px 0; }\n"
".stepper-list::before { content: ''; position: absolute; left: 19px; top: 12px; bottom: 12px; width: 2px; background: #e2e8f0; z-index: 1; }\n"
".step-item { display: flex; align-items: flex-start; gap: 14px; position: relative; z-index: 2; }\n"
".step-dot { width: 20px; height: 20px; border-radius: 50%; background: #fff; border: 3px solid #cbd5e1; display: flex; align-items: center; justify-content: center; flex-shrink: 0; margin-top: 2px; transition: 0.3s; }\n"
".step-item.active .step-dot { border-color: var(--primary); background: var(--primary); box-shadow: 0 0 10px rgba(37,99,235,0.4); }\n"
".step-item.completed .step-dot { border-color: var(--success); background: var(--success); }\n"
".step-content h4 { font-size: 13px; font-weight: 700; }\n"
".step-content p { font-size: 11px; color: var(--text-muted); margin-top: 1px; }\n"
"/* Action Buttons */\n"
".action-buttons-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 14px; }\n"
".btn { border: none; border-radius: 8px; padding: 10px 12px; font-size: 12px; font-weight: 700; cursor: pointer; display: flex; align-items: center; justify-content: center; gap: 6px; transition: 0.2s; }\n"
".btn-preheat { background: #f59e0b; color: #fff; }\n"
".btn-preheat:hover { background: #d97706; }\n"
".btn-roast { background: #16a34a; color: #fff; }\n"
".btn-roast:hover { background: #15803d; }\n"
".btn-pause { background: #475569; color: #fff; }\n"
".btn-pause:hover { background: #334155; }\n"
".btn-stop { background: #ef4444; color: #fff; }\n"
".btn-stop:hover { background: #dc2626; }\n"
".btn-tare { background: #e2e8f0; color: #334155; grid-column: span 2; }\n"
".btn-tare:hover { background: #cbd5e1; }\n"
"/* PWM Actuator Sliders */\n"
".pwm-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 14px; margin-top: 10px; }\n"
".pwm-card { background: #f8fafc; border: 1px solid var(--border); border-radius: 10px; padding: 12px; }\n"
".pwm-card-header { display: flex; align-items: center; gap: 8px; font-size: 13px; font-weight: 700; margin-bottom: 8px; }\n"
".pwm-val-large { font-size: 20px; font-weight: 800; margin-bottom: 8px; }\n"
".pwm-card.res .pwm-val-large { color: #dc2626; }\n"
".pwm-card.blw .pwm-val-large { color: #2563eb; }\n"
".pwm-card.mtr .pwm-val-large { color: #7c3aed; }\n"
".range-slider { -webkit-appearance: none; width: 100%; height: 6px; border-radius: 5px; outline: none; background: #cbd5e1; margin-bottom: 8px; }\n"
".range-slider::-webkit-slider-thumb { -webkit-appearance: none; appearance: none; width: 16px; height: 16px; border-radius: 50%; background: #2563eb; cursor: pointer; }\n"
".pwm-input-row { display: flex; align-items: center; justify-content: flex-end; gap: 4px; }\n"
".pwm-num-box { width: 50px; padding: 4px; text-align: center; border: 1px solid var(--border); border-radius: 6px; font-size: 12px; font-weight: 700; }\n"
".pwm-note { font-size: 11px; color: var(--text-muted); margin-top: 12px; display: flex; align-items: flex-start; gap: 6px; line-height: 1.4; }\n"
"/* Right Column Metric Cards */\n"
".metric-row { display: flex; justify-content: space-between; align-items: baseline; margin-bottom: 8px; }\n"
".metric-label { font-size: 12px; color: var(--text-muted); }\n"
".metric-val-big { font-size: 18px; font-weight: 800; color: var(--text-main); font-variant-numeric: tabular-nums; }\n"
".progress-bar-bg { width: 100%; height: 8px; background: #e2e8f0; border-radius: 4px; overflow: hidden; margin-top: 6px; }\n"
".progress-bar-fill { height: 100%; width: 0%; background: var(--success); transition: width 0.4s ease; border-radius: 4px; }\n"
"/* Additional Info List */\n"
".info-list { display: flex; flex-direction: column; gap: 8px; }\n"
".info-row { display: flex; justify-content: space-between; align-items: center; font-size: 12px; border-bottom: 1px dashed #f1f5f9; padding-bottom: 6px; }\n"
".info-row:last-child { border-bottom: none; }\n"
".info-row .label { color: var(--text-muted); display: flex; align-items: center; gap: 6px; }\n"
".info-row .val { font-weight: 700; }\n"
"/* Emergency Safety Banner */\n"
".alert-banner { display: none; background: #dc2626; color: #fff; padding: 12px 18px; border-radius: 8px; font-size: 14px; font-weight: 700; text-align: center; box-shadow: 0 4px 15px rgba(220,38,38,0.4); animation: pulse 0.8s infinite; margin-bottom: 10px; }\n"
"@media (max-width: 1050px) {\n"
"  .hero-row { grid-template-columns: 1fr; }\n"
"  .dashboard-grid { grid-template-columns: 1fr; }\n"
"  .sidebar { width: 60px; padding: 15px 6px; }\n"
"  .sidebar-brand span, .sidebar-menu span, .sidebar-bottom span { display: none; }\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"\n"
"<!-- Sidebar -->\n"
"<aside class=\"sidebar\">\n"
"  <div>\n"
"    <div class=\"sidebar-brand\">\n"
"      <svg viewBox=\"0 0 24 24\" width=\"20\" height=\"20\" fill=\"currentColor\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 4.1 2.5 7.6 6.1 9.1-.1-.7-.1-1.6.1-2.4l1.3-5.5s-.3-.7-.3-1.7c0-1.6.9-2.8 2.1-2.8 1 0 1.5.8 1.5 1.7 0 1-.7 2.6-1 4-.3 1.2.6 2.2 1.8 2.2 2.2 0 3.7-2.8 3.7-6.1 0-2.5-1.7-4.4-4.7-4.4-3.4 0-5.5 2.5-5.5 5.3 0 1 .4 2.1.9 2.7.1.1.1.2.1.3-.1.4-.3 1.2-.3 1.4 0 .2-.1.2-.3.1C5.6 19.3 5 17.5 5 15.3c0-3.9 3.3-8.6 9.8-8.6 5.2 0 8.7 3.8 8.7 7.9 0 5.3-3 9.3-7.4 9.3-1.5 0-2.9-.8-3.4-1.7l-.9 3.6c-.3 1.2-1.1 2.7-1.7 3.6 1.1.3 2.3.5 3.6.5 5.5 0 10-4.5 10-10S17.5 2 12 2z\"/></svg>\n"
"      <span>Tostadora</span>\n"
"    </div>\n"
"    <nav class=\"sidebar-menu\">\n"
"      <a href=\"#\">\n"
"        <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z\"></path><polyline points=\"9 22 9 12 15 12 15 22\"></polyline></svg>\n"
"        <span>Inicio</span>\n"
"      </a>\n"
"    </nav>\n"
"  </div>\n"
"  <div class=\"sidebar-bottom\">\n"
"    <a onclick=\"sendAction('stop')\" title=\"Apagar todos los actuadores\">\n"
"      <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M18.36 6.64a9 9 0 1 1-12.73 0\"></path><line x1=\"12\" y1=\"2\" x2=\"12\" y2=\"12\"></line></svg>\n"
"      <span>Apagar</span>\n"
"    </a>\n"
"  </div>\n"
"</aside>\n"
"\n"
"<!-- Main Wrapper -->\n"
"<main class=\"main-wrapper\">\n"
"  <!-- Top Header -->\n"
"  <header class=\"top-header\">\n"
"    <div class=\"header-title\">\n"
"      <svg viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"#f59e0b\"><path d=\"M18.5 3H6C4.9 3 4 3.9 4 5v14c0 1.1.9 2 2 2h12.5c2.5 0 4.5-2 4.5-4.5v-9c0-2.5-2-4.5-4.5-4.5zm-6 2c2.2 0 4 1.8 4 4s-1.8 4-4 4-4-1.8-4-4 1.8-4 4-4zm8.5 11.5c0 1.4-1.1 2.5-2.5 2.5H6V5h1.5v6.2c0 .4.5.7.9.5l2.1-1.3 2.1 1.3c.4.2.9-.1.9-.5V5h5c1.4 0 2.5 1.1 2.5 2.5v9z\"/></svg>\n"
"      <span>Tostadora de Café IoT</span>\n"
"    </div>\n"
"    <div class=\"header-status\">\n"
"      <div><span class=\"badge-dot\"></span> <span id=\"net-status\">Conectado (ESP32)</span></div>\n"
"      <div id=\"rtc-clock\">--/--/-- --:--:--</div>\n"
"    </div>\n"
"  </header>\n"
"\n"
"  <!-- Main Content -->\n"
"  <section class=\"content-area\">\n"
"    <!-- Alerta de Seguridad de Emergencia (225 °C) -->\n"
"    <div id=\"alert-banner\" class=\"alert-banner\">\n"
"      ⚠️ ¡CORTE DE SEGURIDAD POR SOBRETEMPERATURA (≥ 225 °C)! PTC apagado, Blower al 100% para protección del grano y tambor.\n"
"    </div>\n"
"\n"
"    <!-- Top Row (3 Hero Cards) -->\n"
"    <div class=\"hero-row\">\n"
"      <!-- Estado Principal -->\n"
"      <div class=\"hero-card\">\n"
"        <div id=\"status-icon\" class=\"status-icon-box\">✓</div>\n"
"        <div class=\"hero-info\">\n"
"          <h2 id=\"status-title\">LISTO</h2>\n"
"          <p id=\"status-subtitle\">Seleccione un modo de tostión para iniciar</p>\n"
"        </div>\n"
"      </div>\n"
"      <!-- Peso Café HX711 -->\n"
"      <div class=\"hero-card\">\n"
"        <div class=\"cafe-icon-box\">\n"
"          <svg viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"#78350f\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2zm1 17.9c-4.4 0-8-3.6-8-8 0-.4 0-.8.1-1.2 1.3 1.2 3.1 2 5.1 2 3.7 0 6.8-2.6 7.6-6.1.7 1.5 1.2 3.3 1.2 5.3 0 4.4-3.6 8-8 8z\"/></svg>\n"
"        </div>\n"
"        <div class=\"hero-info\">\n"
"          <h3 style=\"font-size:13px; color:var(--text-muted);\">Café</h3>\n"
"          <h2 style=\"font-size:18px;\">Peso cargado: <span id=\"weight-val\">0.0</span> g</h2>\n"
"        </div>\n"
"      </div>\n"
"      <!-- Wi-Fi Estado -->\n"
"      <div class=\"hero-card\">\n"
"        <div class=\"wifi-icon-box\">\n"
"          <svg viewBox=\"0 0 24 24\" width=\"24\" height=\"24\" fill=\"#10b981\"><path d=\"M12 3C7.8 3 3.9 4.7.9 7.6l10.4 13c.4.5 1.1.5 1.5 0l10.3-13C20.1 4.7 16.2 3 12 3zm0 4c3.1 0 6 1.2 8.2 3.3l-2.1 2.6C16.5 11.7 14.3 11 12 11s-4.5.7-6.1 1.9L3.8 10.3C6 8.2 8.9 7 12 7zm0 6c1.7 0 3.3.7 4.5 1.8l-4.5 5.6-4.5-5.6c1.2-1.1 2.8-1.8 4.5-1.8z\"/></svg>\n"
"        </div>\n"
"        <div class=\"hero-info\">\n"
"          <h3 style=\"font-size:13px; color:var(--text-muted);\">Wi-Fi</h3>\n"
"          <h2 id=\"wifi-card-title\" style=\"font-size:16px;\">Conectado</h2>\n"
"          <p id=\"wifi-ip-val\" style=\"font-size:11px;\">192.168.4.1</p>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Main 3-Column Grid -->\n"
"    <div class=\"dashboard-grid\">\n"
"      <!-- Columna 1: Selección de Modo y Potencia PWM -->\n"
"      <div>\n"
"        <!-- Selección de Modo -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3>Selecciona el modo de tostión</h3>\n"
"          </div>\n"
"          <div class=\"modes-row\">\n"
"            <!-- Modo 1 -->\n"
"            <div id=\"mode-card-0\" class=\"mode-box m1 selected\" onclick=\"selectMode(0)\">\n"
"              <svg viewBox=\"0 0 24 24\" fill=\"#10b981\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2zm1 17.9c-4.4 0-8-3.6-8-8 0-.4 0-.8.1-1.2 1.3 1.2 3.1 2 5.1 2 3.7 0 6.8-2.6 7.6-6.1.7 1.5 1.2 3.3 1.2 5.3 0 4.4-3.6 8-8 8z\"/></svg>\n"
"              <div class=\"mode-title\" style=\"color:#10b981;\">Tostión 1</div>\n"
"              <div class=\"mode-sub\">(Bajo / Clara)</div>\n"
"              <div class=\"mode-target\">198°C | 9 min</div>\n"
"            </div>\n"
"            <!-- Modo 2 -->\n"
"            <div id=\"mode-card-1\" class=\"mode-box m2\" onclick=\"selectMode(1)\">\n"
"              <svg viewBox=\"0 0 24 24\" fill=\"#2563eb\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2zm1 17.9c-4.4 0-8-3.6-8-8 0-.4 0-.8.1-1.2 1.3 1.2 3.1 2 5.1 2 3.7 0 6.8-2.6 7.6-6.1.7 1.5 1.2 3.3 1.2 5.3 0 4.4-3.6 8-8 8z\"/></svg>\n"
"              <div class=\"mode-title\" style=\"color:#2563eb;\">Tostión 2</div>\n"
"              <div class=\"mode-sub\">(Medio / Bal.)</div>\n"
"              <div class=\"mode-target\">208°C | 11 min</div>\n"
"            </div>\n"
"            <!-- Modo 3 -->\n"
"            <div id=\"mode-card-2\" class=\"mode-box m3\" onclick=\"selectMode(2)\">\n"
"              <svg viewBox=\"0 0 24 24\" fill=\"#f97316\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2zm1 17.9c-4.4 0-8-3.6-8-8 0-.4 0-.8.1-1.2 1.3 1.2 3.1 2 5.1 2 3.7 0 6.8-2.6 7.6-6.1.7 1.5 1.2 3.3 1.2 5.3 0 4.4-3.6 8-8 8z\"/></svg>\n"
"              <div class=\"mode-title\" style=\"color:#f97316;\">Tostión 3</div>\n"
"              <div class=\"mode-sub\">(Alto / Oscura)</div>\n"
"              <div class=\"mode-target\">218°C | 13 min</div>\n"
"            </div>\n"
"          </div>\n"
"          <!-- Modo Manual -->\n"
"          <div id=\"mode-card-3\" class=\"mode-manual\" onclick=\"selectMode(3)\">\n"
"            <svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"3\"></circle><path d=\"M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z\"></path></svg>\n"
"            <div>\n"
"              <div style=\"font-size:13px; font-weight:700; color:var(--purple);\">Manual</div>\n"
"              <div style=\"font-size:11px; color:var(--text-muted);\">Configuración personalizada de PWM</div>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Controles de Potencia (PWM) -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3>Controles de potencia (PWM)</h3>\n"
"          </div>\n"
"          <div class=\"pwm-grid\">\n"
"            <!-- Resistencia PTC -->\n"
"            <div class=\"pwm-card res\">\n"
"              <div class=\"pwm-card-header\">\n"
"                <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"#dc2626\"><path d=\"M12 2c-5.33 4-8 8-8 12 0 4.42 3.58 8 8 8s8-3.58 8-8c0-4-2.67-8-8-12zm0 18c-3.31 0-6-2.69-6-6 0-2.97 1.87-5.96 5-8.77v3.77c0 .55.45 1 1 1s1-.45 1-1v-3.77c3.13 2.81 5 5.8 5 8.77 0 3.31-2.69 6-6 6z\"/></svg>\n"
"                <span>Resistencia</span>\n"
"              </div>\n"
"              <div id=\"ptc-val-text\" class=\"pwm-val-large\">0%</div>\n"
"              <input type=\"range\" id=\"slider-ptc\" class=\"range-slider\" min=\"0\" max=\"100\" value=\"0\" oninput=\"onSliderChange('ptc', this.value)\">\n"
"              <div class=\"pwm-input-row\">\n"
"                <input type=\"number\" id=\"num-ptc\" class=\"pwm-num-box\" min=\"0\" max=\"100\" value=\"0\" onchange=\"onSliderChange('ptc', this.value)\">\n"
"                <span style=\"font-size:11px; font-weight:700;\">%</span>\n"
"              </div>\n"
"            </div>\n"
"            <!-- Ventilador Blower -->\n"
"            <div class=\"pwm-card blw\">\n"
"              <div class=\"pwm-card-header\">\n"
"                <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"#2563eb\"><path d=\"M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2zm1 3.1a2 2 0 0 1 2 2c0 1.5-1.5 2.5-3 2.9V5.1zm-2 13.8a2 2 0 0 1-2-2c0-1.5 1.5-2.5 3-2.9v4.9zm-4.9-6.9a2 2 0 0 1 2-2c1.5 0 2.5 1.5 2.9 3H6.1zm11.8 0c-.4-1.5-1.4-3-2.9-3a2 2 0 0 1 2 2h.9z\"/></svg>\n"
"                <span>Ventilador</span>\n"
"              </div>\n"
"              <div id=\"blw-val-text\" class=\"pwm-val-large\">0%</div>\n"
"              <input type=\"range\" id=\"slider-blw\" class=\"range-slider\" min=\"0\" max=\"100\" value=\"0\" oninput=\"onSliderChange('blw', this.value)\">\n"
"              <div class=\"pwm-input-row\">\n"
"                <input type=\"number\" id=\"num-blw\" class=\"pwm-num-box\" min=\"0\" max=\"100\" value=\"0\" onchange=\"onSliderChange('blw', this.value)\">\n"
"                <span style=\"font-size:11px; font-weight:700;\">%</span>\n"
"              </div>\n"
"            </div>\n"
"            <!-- Motor Tambor -->\n"
"            <div class=\"pwm-card mtr\">\n"
"              <div class=\"pwm-card-header\">\n"
"                <svg viewBox=\"0 0 24 24\" width=\"18\" height=\"18\" fill=\"#7c3aed\"><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\"/><circle cx=\"12\" cy=\"12\" r=\"3\" fill=\"currentColor\"/></svg>\n"
"                <span>Motor tambor</span>\n"
"              </div>\n"
"              <div id=\"mtr-val-text\" class=\"pwm-val-large\">0%</div>\n"
"              <input type=\"range\" id=\"slider-mtr\" class=\"range-slider\" min=\"0\" max=\"100\" value=\"0\" oninput=\"onSliderChange('mtr', this.value)\">\n"
"              <div class=\"pwm-input-row\">\n"
"                <input type=\"number\" id=\"num-mtr\" class=\"pwm-num-box\" min=\"0\" max=\"100\" value=\"0\" onchange=\"onSliderChange('mtr', this.value)\">\n"
"                <span style=\"font-size:11px; font-weight:700;\">%</span>\n"
"              </div>\n"
"            </div>\n"
"          </div>\n"
"          <div class=\"pwm-note\">\n"
"            <svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"#3b82f6\" style=\"flex-shrink:0;\"><circle cx=\"12\" cy=\"12\" r=\"10\" stroke=\"currentColor\" stroke-width=\"2\" fill=\"none\"/><line x1=\"12\" y1=\"16\" x2=\"12\" y2=\"12\" stroke=\"currentColor\" stroke-width=\"2\"/><line x1=\"12\" y1=\"8\" x2=\"12.01\" y2=\"8\" stroke=\"currentColor\" stroke-width=\"2\"/></svg>\n"
"            <span>Los valores de PWM son una referencia. El sistema ajusta automáticamente la potencia según el perfil de tostión seleccionado y protege los límites eléctricos (10V / 7A).</span>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- Columna 2: Proceso de Tostión (Stepper) y Acciones -->\n"
"      <div>\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3>Proceso de tostión</h3>\n"
"            <span id=\"process-badge\" class=\"badge-state ready\">Estado: LISTO</span>\n"
"          </div>\n"
"          <div class=\"stepper-list\">\n"
"            <!-- Paso 1: LISTO -->\n"
"            <div id=\"step-0\" class=\"step-item completed\">\n"
"              <div class=\"step-dot\">✓</div>\n"
"              <div class=\"step-content\">\n"
"                <h4>LISTO</h4>\n"
"                <p>Esperando inicio de precalentamiento</p>\n"
"              </div>\n"
"            </div>\n"
"            <!-- Paso 2: PRECALENTANDO -->\n"
"            <div id=\"step-1\" class=\"step-item\">\n"
"              <div class=\"step-dot\">2</div>\n"
"              <div class=\"step-content\">\n"
"                <h4>Precalentando</h4>\n"
"                <p>Calentando cámara a 180°C - 190°C</p>\n"
"              </div>\n"
"            </div>\n"
"            <!-- Paso 3: TOSTIÓN -->\n"
"            <div id=\"step-2\" class=\"step-item\">\n"
"              <div class=\"step-dot\">3</div>\n"
"              <div class=\"step-content\">\n"
"                <h4>Tostión</h4>\n"
"                <p>Aplicando perfil de tostión al grano</p>\n"
"              </div>\n"
"            </div>\n"
"            <!-- Paso 4: ENFRIAMIENTO -->\n"
"            <div id=\"step-3\" class=\"step-item\">\n"
"              <div class=\"step-dot\">4</div>\n"
"              <div class=\"step-content\">\n"
"                <h4>Enfriamiento</h4>\n"
"                <p>Ventilador ON, resistencia OFF</p>\n"
"              </div>\n"
"            </div>\n"
"          </div>\n"
"\n"
"          <!-- Botones de Control Rápido -->\n"
"          <div class=\"action-buttons-grid\">\n"
"            <button id=\"btn-preheat\" class=\"btn btn-preheat\" onclick=\"sendAction('start_preheat')\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><path d=\"M12 2c-5.33 4-8 8-8 12 0 4.42 3.58 8 8 8s8-3.58 8-8c0-4-2.67-8-8-12z\"/></svg>\n"
"              <span>Precalentar (185°C)</span>\n"
"            </button>\n"
"            <button id=\"btn-roast\" class=\"btn btn-roast\" onclick=\"sendAction('start_roast')\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2z\"/></svg>\n"
"              <span>Iniciar Tostión</span>\n"
"            </button>\n"
"            <button id=\"btn-pause\" class=\"btn btn-pause\" onclick=\"sendAction('pause_resume')\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><rect x=\"6\" y=\"4\" width=\"4\" height=\"16\"/><rect x=\"14\" y=\"4\" width=\"4\" height=\"16\"/></svg>\n"
"              <span id=\"btn-pause-text\">Pausar</span>\n"
"            </button>\n"
"            <button id=\"btn-stop\" class=\"btn btn-stop\" onclick=\"sendAction('stop')\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\"/></svg>\n"
"              <span>Detener</span>\n"
"            </button>\n"
"            <button class=\"btn btn-tare\" onclick=\"sendAction('tare')\">\n"
"              <svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><line x1=\"2\" y1=\"12\" x2=\"22\" y2=\"12\"/><circle cx=\"12\" cy=\"12\" r=\"3\"/></svg>\n"
"              <span>Tarar Báscula HX711 (Poner en Cero)</span>\n"
"            </button>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"\n"
"      <!-- Columna 3: Tiempo, Temperatura, Consumo e Información -->\n"
"      <div>\n"
"        <!-- Tiempo -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3><svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><polyline points=\"12 6 12 12 16 14\"></polyline></svg> Tiempo</h3>\n"
"          </div>\n"
"          <div class=\"metric-row\">\n"
"            <span class=\"metric-label\">Tiempo configurado</span>\n"
"            <span id=\"time-config\" class=\"metric-val-big\">09:00</span>\n"
"          </div>\n"
"          <div class=\"metric-row\">\n"
"            <span class=\"metric-label\">Tiempo restante</span>\n"
"            <span id=\"time-remaining\" class=\"metric-val-big\" style=\"color:#2563eb;\">09:00</span>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Temperatura -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3><svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M14 14.76V3.5a2.5 2.5 0 0 0-5 0v11.26a4.5 4.5 0 1 0 5 0z\"></path></svg> Temperatura</h3>\n"
"          </div>\n"
"          <div class=\"metric-row\">\n"
"            <span class=\"metric-label\">Actual / Objetivo</span>\n"
"            <span class=\"metric-val-big\"><span id=\"temp-act\">25.0</span> / <span id=\"temp-tgt\">198</span> °C</span>\n"
"          </div>\n"
"          <div class=\"progress-bar-bg\">\n"
"            <div id=\"temp-progress\" class=\"progress-bar-fill\"></div>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Consumo de Energía -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3><svg viewBox=\"0 0 24 24\" width=\"16\" height=\"16\" fill=\"#f59e0b\"><polygon points=\"13 2 3 14 12 14 11 22 21 10 12 10 13 2\"></polygon></svg> Consumo de energía</h3>\n"
"          </div>\n"
"          <div class=\"metric-row\">\n"
"            <span class=\"metric-label\">Instantáneo</span>\n"
"            <span id=\"pwr-instant\" class=\"metric-val-big\">0.0 kW</span>\n"
"          </div>\n"
"          <div class=\"metric-row\">\n"
"            <span class=\"metric-label\">Acumulado</span>\n"
"            <span id=\"pwr-accum\" class=\"metric-val-big\">0.00 kWh</span>\n"
"          </div>\n"
"        </div>\n"
"\n"
"        <!-- Información Adicional -->\n"
"        <div class=\"card\">\n"
"          <div class=\"card-header\">\n"
"            <h3>Información adicional</h3>\n"
"          </div>\n"
"          <div class=\"info-list\">\n"
"            <div class=\"info-row\">\n"
"              <span class=\"label\"><svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><path d=\"M12 2C6.5 2 2 6.5 2 12c0 5.5 4.5 10 10 10s10-4.5 10-10C22 6.5 17.5 2 12 2z\"/></svg> Temperatura del tambor</span>\n"
"              <span id=\"info-drum-temp\" class=\"val\">25.0 °C</span>\n"
"            </div>\n"
"            <div class=\"info-row\">\n"
"              <span class=\"label\"><svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"/></svg> Velocidad del tambor (PWM)</span>\n"
"              <span id=\"info-drum-pwm\" class=\"val\">0 %</span>\n"
"            </div>\n"
"            <div class=\"info-row\">\n"
"              <span class=\"label\"><svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><path d=\"M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2z\"/></svg> Velocidad del ventilador (PWM)</span>\n"
"              <span id=\"info-fan-pwm\" class=\"val\">0 %</span>\n"
"            </div>\n"
"            <div class=\"info-row\">\n"
"              <span class=\"label\"><svg viewBox=\"0 0 24 24\" width=\"14\" height=\"14\" fill=\"currentColor\"><rect x=\"4\" y=\"4\" width=\"16\" height=\"16\" rx=\"2\"/></svg> Registro MicroSD</span>\n"
"              <span id=\"info-sd\" class=\"val\" style=\"color:#10b981;\">Montada</span>\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"  </section>\n"
"</main>\n"
"\n"
"<script>\n"
"var currentMode = 0;\n"
"var isPaused = false;\n"
"\n"
"function selectMode(m) {\n"
"  currentMode = m;\n"
"  for (var i = 0; i < 4; i++) {\n"
"    var el = document.getElementById('mode-card-' + i);\n"
"    if (el) {\n"
"      if (i === m) el.classList.add('selected');\n"
"      else el.classList.remove('selected');\n"
"    }\n"
"  }\n"
"  fetch('/api/command', {\n"
"    method: 'POST',\n"
"    headers: {'Content-Type': 'application/json'},\n"
"    body: JSON.stringify({ action: 'set_mode', mode: m })\n"
"  }).catch(function(e){ console.error(e); });\n"
"}\n"
"\n"
"function onSliderChange(actuator, val) {\n"
"  document.getElementById(actuator + '-val-text').innerText = val + '%';\n"
"  document.getElementById('num-' + actuator).value = val;\n"
"  document.getElementById('slider-' + actuator).value = val;\n"
"  var payload = { action: 'set_pwm' };\n"
"  payload[actuator] = parseInt(val);\n"
"  fetch('/api/command', {\n"
"    method: 'POST',\n"
"    headers: {'Content-Type': 'application/json'},\n"
"    body: JSON.stringify(payload)\n"
"  }).catch(function(e){ console.error(e); });\n"
"}\n"
"\n"
"function sendAction(action) {\n"
"  fetch('/api/command', {\n"
"    method: 'POST',\n"
"    headers: {'Content-Type': 'application/json'},\n"
"    body: JSON.stringify({ action: action })\n"
"  }).catch(function(e){ console.error(e); });\n"
"}\n"
"\n"
"function formatMMSS(sec) {\n"
"  if (sec < 0) sec = 0;\n"
"  var m = Math.floor(sec / 60);\n"
"  var s = sec % 60;\n"
"  return (m < 10 ? '0' : '') + m + ':' + (s < 10 ? '0' : '') + s;\n"
"}\n"
"\n"
"function updateDashboard() {\n"
"  fetch('/api/status')\n"
"    .then(function(res) { return res.json(); })\n"
"    .then(function(data) {\n"
"      // Header & Wi-Fi\n"
"      document.getElementById('rtc-clock').innerText = data.rtc_time || '--:--:--';\n"
"      document.getElementById('wifi-ip-val').innerText = data.wifi_ip || '192.168.4.1';\n"
"      document.getElementById('net-status').innerText = data.wifi_connected ? 'Conectado (' + data.wifi_ip + ')' : 'Modo SoftAP (192.168.4.1)';\n"
"\n"
"      // Alerta de Sobretemperatura\n"
"      var banner = document.getElementById('alert-banner');\n"
"      if (data.emergency) {\n"
"        banner.style.display = 'block';\n"
"      } else {\n"
"        banner.style.display = 'none';\n"
"      }\n"
"\n"
"      // Hero Status\n"
"      var iconBox = document.getElementById('status-icon');\n"
"      iconBox.className = 'status-icon-box';\n"
"      if (data.state === 'STANDBY') {\n"
"        iconBox.innerText = '✓';\n"
"        document.getElementById('status-title').innerText = 'LISTO';\n"
"        document.getElementById('status-subtitle').innerText = 'Seleccione un modo y comience el precalentamiento';\n"
"        document.getElementById('process-badge').innerText = 'Estado: LISTO';\n"
"        document.getElementById('process-badge').className = 'badge-state ready';\n"
"      } else if (data.state === 'PREHEATING') {\n"
"        iconBox.classList.add('preheat');\n"
"        iconBox.innerText = '🔥';\n"
"        document.getElementById('status-title').innerText = 'PRECALENTANDO';\n"
"        document.getElementById('status-subtitle').innerText = 'Elevando temperatura del tambor a ' + data.temp_target + ' °C';\n"
"        document.getElementById('process-badge').innerText = 'Estado: PRECALENTANDO';\n"
"        document.getElementById('process-badge').className = 'badge-state preheat';\n"
"      } else if (data.state === 'CHARGING') {\n"
"        iconBox.classList.add('preheat');\n"
"        iconBox.innerText = '☕';\n"
"        document.getElementById('status-title').innerText = 'PRECALENTADO (CARGA)';\n"
"        document.getElementById('status-subtitle').innerText = 'Cámara lista a 185°C. Inserte el grano de café y pulse Iniciar Tostión';\n"
"        document.getElementById('process-badge').innerText = 'Estado: CARGA DE CAFÉ';\n"
"        document.getElementById('process-badge').className = 'badge-state preheat';\n"
"      } else if (data.state === 'ROASTING') {\n"
"        iconBox.classList.add('roast');\n"
"        iconBox.innerText = '☕';\n"
"        document.getElementById('status-title').innerText = 'TOSTIÓN EN MARCHA';\n"
"        document.getElementById('status-subtitle').innerText = 'Aplicando perfil ' + data.mode_name + ' (Obj: ' + data.temp_target + ' °C)';\n"
"        document.getElementById('process-badge').innerText = 'Estado: TOSTIÓN';\n"
"        document.getElementById('process-badge').className = 'badge-state active';\n"
"      } else if (data.state === 'PAUSED') {\n"
"        iconBox.innerText = '⏸';\n"
"        document.getElementById('status-title').innerText = 'PAUSADO';\n"
"        document.getElementById('status-subtitle').innerText = 'Actuadores en reposo hasta reanudar la secuencia';\n"
"        document.getElementById('process-badge').innerText = 'Estado: PAUSA';\n"
"        document.getElementById('process-badge').className = 'badge-state';\n"
"      } else if (data.state === 'COOLDOWN') {\n"
"        iconBox.classList.add('cool');\n"
"        iconBox.innerText = '❄';\n"
"        document.getElementById('status-title').innerText = 'ENFRIAMIENTO';\n"
"        document.getElementById('status-subtitle').innerText = 'Disipando calor del tambor. Ventilador a plena potencia';\n"
"        document.getElementById('process-badge').innerText = 'Estado: ENFRIAMIENTO';\n"
"        document.getElementById('process-badge').className = 'badge-state cool';\n"
"      } else if (data.state === 'EMERGENCY') {\n"
"        iconBox.classList.add('alarm');\n"
"        iconBox.innerText = '⚠️';\n"
"        document.getElementById('status-title').innerText = '¡EMERGENCIA 225°C!';\n"
"        document.getElementById('status-subtitle').innerText = 'CORTE INMEDIATO POR SOBRETEMPERATURA. Ventilador al 100%';\n"
"        document.getElementById('process-badge').innerText = 'Estado: EMERGENCIA';\n"
"        document.getElementById('process-badge').className = 'badge-state active';\n"
"      }\n"
"\n"
"      // Stepper highlight\n"
"      for (var s = 0; s < 4; s++) {\n"
"        var stepEl = document.getElementById('step-' + s);\n"
"        if (stepEl) {\n"
"          stepEl.className = 'step-item';\n"
"          if (data.step_index > s) stepEl.classList.add('completed');\n"
"          else if (data.step_index === s) stepEl.classList.add('active');\n"
"        }\n"
"      }\n"
"\n"
"      // Peso HX711\n"
"      document.getElementById('weight-val').innerText = data.weight_g !== undefined ? data.weight_g.toFixed(1) : '--.-';\n"
"\n"
"      // Tiempos\n"
"      document.getElementById('time-config').innerText = formatMMSS(data.time_config_sec || 0);\n"
"      document.getElementById('time-remaining').innerText = formatMMSS(data.time_remaining_sec || 0);\n"
"\n"
"      // Temperaturas y barra\n"
"      var tAct = data.temp_actual || 0;\n"
"      var tTgt = data.temp_target || 1;\n"
"      document.getElementById('temp-act').innerText = tAct.toFixed(1);\n"
"      document.getElementById('temp-tgt').innerText = tTgt.toFixed(0);\n"
"      var pct = Math.min(100, Math.max(0, (tAct / tTgt) * 100));\n"
"      document.getElementById('temp-progress').style.width = pct.toFixed(1) + '%';\n"
"      if (tAct >= tTgt) document.getElementById('temp-progress').style.background = '#f97316';\n"
"      else document.getElementById('temp-progress').style.background = '#10b981';\n"
"\n"
"      // Potencia y Energía Estimada\n"
"      document.getElementById('pwr-instant').innerText = (data.power_w / 1000.0).toFixed(2) + ' kW (' + data.power_w.toFixed(0) + ' W)';\n"
"      document.getElementById('pwr-accum').innerText = data.energy_kwh.toFixed(4) + ' kWh';\n"
"\n"
"      // Info Adicional\n"
"      document.getElementById('info-drum-temp').innerText = tAct.toFixed(1) + ' °C';\n"
"      document.getElementById('info-drum-pwm').innerText = data.pwm_mtr + ' %';\n"
"      document.getElementById('info-fan-pwm').innerText = data.pwm_blw + ' %';\n"
"      document.getElementById('info-sd').innerText = data.sd_ok ? 'Montada (/sdcard)' : 'No detectada';\n"
"      document.getElementById('info-sd').style.color = data.sd_ok ? '#10b981' : '#f59e0b';\n"
"\n"
"      // Sliders & Textos de PWM\n"
"      document.getElementById('ptc-val-text').innerText = data.pwm_ptc + '%';\n"
"      document.getElementById('blw-val-text').innerText = data.pwm_blw + '%';\n"
"      document.getElementById('mtr-val-text').innerText = data.pwm_mtr + '%';\n"
"      document.getElementById('slider-ptc').value = data.pwm_ptc;\n"
"      document.getElementById('num-ptc').value = data.pwm_ptc;\n"
"      document.getElementById('slider-blw').value = data.pwm_blw;\n"
"      document.getElementById('num-blw').value = data.pwm_blw;\n"
"      document.getElementById('slider-mtr').value = data.pwm_mtr;\n"
"      document.getElementById('num-mtr').value = data.pwm_mtr;\n"
"\n"
"      // Botón pausa texto\n"
"      if (data.state === 'PAUSED') {\n"
"        document.getElementById('btn-pause-text').innerText = 'Reanudar';\n"
"      } else {\n"
"        document.getElementById('btn-pause-text').innerText = 'Pausar';\n"
"      }\n"
"\n"
"      // Sincronizar selección de modo si no estamos editando\n"
"      if (data.mode !== undefined && data.mode !== currentMode) {\n"
"        currentMode = data.mode;\n"
"        for (var k = 0; k < 4; k++) {\n"
"          var card = document.getElementById('mode-card-' + k);\n"
"          if (card) {\n"
"            if (k === currentMode) card.classList.add('selected');\n"
"            else card.classList.remove('selected');\n"
"          }\n"
"        }\n"
"      }\n"
"    })\n"
"    .catch(function(err) {\n"
"      console.warn('Error al actualizar telemetría:', err);\n"
"    });\n"
"}\n"
"\n"
"// Refresco continuo a 800 ms\n"
"setInterval(updateDashboard, 800);\n"
"updateDashboard();\n"
"</script>\n"
"</body>\n"
"</html>\n";

#endif // WEB_DASHBOARD_H
